version: .{build}

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

image:
  - Visual Studio 2022
  - Ubuntu

environment:
  CAKE_SETTINGS_SKIPVERIFICATION: true
  CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

install:
  - ps: dotnet new tool-manifest
  - ps: dotnet tool install Cake.Tool --version 1.3.0
  - ps: dotnet tool install GitVersion.Tool --version 5.8.2

test: off

matrix:
  fast_finish: true

for:

# Linux build
-
  matrix:
    except:
      - image: Visual Studio 2022

  clone_folder: ~/work/template.classlib

  install:
    - ps: dotnet new tool-manifest
    - ps: dotnet tool install Cake.Tool --version 1.3.0
    - ps: dotnet tool install GitVersion.Tool --version 5.8.2

  build_script:
    - sh: SemVer=$(dotnet dotnet-gitversion -showvariable InformationalVersion)
    - sh: dotnet pack ./src -c Release /p:Version=$SemVer
    - sh: dotnet dotnet-gitversion /UpdateAssemblyInfo ./src/templates/src/common/AssemblyVersion.cs /EnsureAssemblyInfo
    - sh: ./test-templates.sh


# Windows build
-
  matrix:
    only:
      - image: Visual Studio 2022

  clone_folder: c:\work\template.classlib

  cache:
    - c:\tmp\cake\tools -> appveyor.yml

  environment:
    appveyor_cache_entry_zip_args: -t7z -m0=lzma -mx=5 -ms=on
    CAKE_PATHS_TOOLS: c:\tmp\cake\tools\
    GITHUB_TOKEN:
      secure: oWsS4pNwWN+Y2KV6bCr8yKthXMVhVY3WORd7vSNXiwFT3VH7gdBGVNeFg/McrbzY

  install:
    - ps: dotnet tool install -g Cake.Tool --version 1.3.0
    - ps: dotnet tool install -g GitVersion.Tool --version 5.8.2
    
  build_script:
    - ps: $GitVersion = dotnet gitversion | ConvertFrom-Json
    - ps: Write-Output $GitVersion
    - ps: dotnet --info
    - ps: dotnet pack ./src -c Release /p:Version=$GitVersion.SemVer -o Drops/Packages/ -v d
    - ps: dotnet-gitversion /UpdateAssemblyInfo ./src/templates/src/common/AssemblyVersion.cs /EnsureAssemblyInfo
    - ps: test-templates.cmd

  artifacts:
    - path: Drops/Packages/*.nupkg
      name: NuGet packages

    - path: Drops/Packages/*.snupkg
      name: NuGet symbol packages
      type: NuGetPackage
  #  - path: Drops/Inspections/CodeDuplicates.html
  #    name: CodeDuplicates
  #  - path: Drops/Inspections/CodeInspections.html
  #    name: CodeInspections

  deploy:
    - provider: NuGet
      name: Pre-release
      api_key:
        secure: 8vpp3v6A7cXo+jJPb4ZcyZ5KdfNgcElKlJHI/lB+dfbycWfANsPeAToD/Q9z6v4z
      on:
        branch:
          - develop
          - /release\/v.*/
          - /hotfix\/v.*/

    - provider: NuGet
      name: Tagged release
      api_key:
        secure: 8vpp3v6A7cXo+jJPb4ZcyZ5KdfNgcElKlJHI/lB+dfbycWfANsPeAToD/Q9z6v4z
      on:
        appveyor_repo_tag: true
